baseurl = "https://zlxamx.github.io/"
languageCode = "zh-cn"
title = "LuxiBlog"

# Theme i18n support
defaultContentLanguage = "zh"

# Set hasCJKLanguage to true for Chinese
hasCJKLanguage = true

disqusShortname = ""

[pagination]
    pagerSize = 5

mainSections = ["post"]
rssFullContent = true
favicon = "img/favicon.png"

SortBy = "default"

[footer]
    since = 2026
    customText = ""

[dateFormat]
    published = ":date_full"
    lastUpdated = ":date_full"
