baseURL = "https://luxi.blog/"
languageCode = "zh-cn"
title = "LuxiBlog"
theme = "typo"

hasCJKLanguage = true
paginate = 10

[params]
description = "思考者，也是实践者"
homeIntroContent = "思考者，也是实践者。这里记录极简主义、生活、思考与影视。"
homeCollection = "post"
homeCollectionTitle = "最近文章"
paginationSize = 10
listSummaries = true
colorPalette = "linen"
mainSections = ["post"]

[params.breadcrumbs]
enabled = false

[[params.social]]
name = "github"
url = "https://github.com/zlxamx"

[[params.menu]]
name = "文章"
url = "/post"
weight = 1

[[params.menu]]
name = "标签"
url = "/tags"
weight = 2
